# Generated by Django 5.2.5 on 2025-09-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('info_link', models.URLField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book_id')},
            },
        ),
    ]
