# Generated by Django 5.2.5 on 2025-09-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='authors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='book_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='info_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_at',
        ),
    ]
