# Generated by Django 5.2.5 on 2025-09-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore1', '0002_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='authors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='info_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
